### ISSUE TITLE
missing main

### ISSUE THREAD

**Issue by peymanr** [mhdzli/simorq#10]
Beautiful work. It looks like 'main' is missing? 

```
style.scss:1: Error: File to import not found or unreadable: main. (SassC::SyntaxError)
        on line 1:1 of style.scss
>> @import 'main';
```

**Comment by mhdzli** [comment]
[here](https://github.com/mhdzli/simorq/blob/1106bab2964e0d18e2f2cd5f91124a951f8efc5c/src/assets/css/style.scss#L4C1-L4C16)
