### ISSUE TITLE
قالب برای گیت هاب پیچ

### ISSUE THREAD

**Issue by mimsadAlef** [mhdzli/simorq#2]
سلام آقای زینلی
 لطفا یه قالب مناسب برای گیت هاب پیج رو هم بسازید
برای شمسی سازی تاریخ ها یه سری توابع با جاوااسکریپت هستند
اگه می خواید یه ریپازوری درست کنید و به من دسترسی بدید من خودم انجام می دم

**Comment by mhdzli** [comment]
سلام
قالب‌های با مجوز آراد از جکیل فراوانند.
می‌تونید یکیشون رو انتخاب کنید و تغییرات لازم رو روش اعمال کنید.
من دو تا قالب جکیل دیگه رو هم دارم آماده می‌کنم و سعی می‌کنم برای تبدیل تاریخ توی فایل کانفیگ دو تا انتخاب بذارم که یکیش از جاوااسکریپت استفاده کنه و برای گیت‌هاب پیج مناسب باشه.
یه ریپوزیتوری هم اضافه می‌کنم و بهتون دسترسی می‌دم که با هم پیش بریم :-)
