### ISSUE TITLE
Add Comments to website

### ISSUE THREAD

**Issue by pourmand1376** [mhdzli/simorq#5]
Do you know any comment service which we can use without censorship? I am currently using `disqus` which is censored in Iran. 

If you know of any service, let me know. I can also add it to this theme.

**Comment by mhdzli** [comment]
I'm using [mastodon](https://www.zmim.ir/mastodon-comments/) for comments right now. But there are other ways e.g:
https://mehdix.ir/static-comments.html
https://mehdix.ir/cgi-comments.html

**Comment by pourmand1376** [comment]
Thank you for your quick answer!
